/**
 * Wraps the built viewer IIFE (dist-viewer/flowviewer.js) into a committed
 * TypeScript module exporting the code as a string, so exportHtml.ts can
 * embed it into self-contained .html exports. Run via `npm run generate-viewer`.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const code = readFileSync('dist-viewer/flowviewer.js', 'utf8');
const out =
  '/** AUTO-GENERATED by `npm run generate-viewer` — do not edit by hand.\n' +
  ' *  Source: src/viewer/viewerMain.ts, built by vite.viewer.config.ts. */\n' +
  `export const VIEWER_RUNTIME: string = ${JSON.stringify(code)};\n`;
writeFileSync('src/viewer/runtime.generated.ts', out);
console.log(`wrote src/viewer/runtime.generated.ts (${(out.length / 1024).toFixed(1)} kB)`);
